config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'home#index'

  resources :autors do
      member do
        get :book
      end
  end

  resources :books do
    resources :orders
  end

  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/autor.rb
class Autor < ApplicationRecord
 has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  
  has_many :book
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
  	validates :price, numericality: {greater_than: 0}
    validates :quantities, numericality: {greater_than: 0}


  belongs_to :autor
  has_many :orders

   def self.categories
  ["Romance", "Terror", "Adventure", "Science", "Motivational"]
end

end

app/models/order.rb
class Order < ApplicationRecord
	   validates :Quantity	, presence: true, numericality: {greater_than: 0}
    belongs_to :book

    before_create :set_dates

    validate :no_esta_rentado

    def no_esta_rentado
    if Book.find_by(id: book_id).orders.any?
      @order = Book.find_by(id: book_id).orders.order("created_at").last
      if  @order.order_end_at > Date.today
        errors.add(:order_start_at, "Este carro esta prestado.")
      end
    end
  end

    protected

    def set_dates
      self.order_end_at = Date.today 
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_autor, :authenticate
  before_action :authenticate

  def login(autor)
  	session[:autor_id] = autor.id
  	redirect_to book_autor_path(autor.id)
  end

  def logout
  	reset_session
  	redirect_to root_path
  end

  def current_autor
    if session[:autor_id]
      @current_autor = Autor.find(session[:autor_id])
    end
  end

  def authenticate
    unless current_autor
      redirect_to root_path
    end
  end
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  skip_before_action :authenticate

  def new
    @autor = Autor.new
  end

  def create
    @autor = Autor.new(autor_params)

    if @autor.save
      login(@autor)
      AutorMailer.signup_email(@autor).deliver
    else
      render :new
    end
  end

  def book
    @books = Book.where(["autor_id = ?", current_autor.id])
  end

  protected

  def autor_params
    params.require(:autor).permit!
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  skip_before_action :authenticate, except: [:new, :create, :edit, :update, :destroy]

  def index
    @books = Book.order(:title)
  end

  def show
    @book = Book.find(params[:id])

  end
 
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    @book.autor_id = current_autor.id
    
    if @book.save
      redirect_to books_path, notice: "Se agrego exitosamente."
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(book_params)
      redirect_to book_path(@book),  notice: "Se edito con exito."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path,  notice: "Se borro con exito."
  end

  protected

  def book_params
    params.require(:book).permit!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate
  def index
  end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	  skip_before_action :authenticate

  def new
      @book = Book.find(params[:book_id])
      @order = @book.orders.build
  end

  def create
    @book = Book.find(params[:book_id])
    @order = @book.orders.build(orders_params)
    @order.total = @book.price * @order.Quantity	
 
    if @order.save
      OwnerNotifierMailer.order_email(Owner.find_by(id: @book.autor_id), @order).deliver
      redirect_to @book,  notice: "Book: "+@book.title+" Compra de Libro: "+@order.order_end_at.to_formatted_s(:long)+"."
    else
      render :new
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    @order = @book.orders.find(params[:id])
    @order.destroy
    redirect_to @book,  notice: "Se borro con exito."
  end

protected

  def orders_params
        params.require(:order).permit!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :authenticate

  def new
    if current_autor
      redirect_to root_path
    end
  end

  def create
    password = params[:session][:password]
    email = params[:session][:email]


    @autor = Autor.find_by(email: email)

    if @autor && @autor.authenticate(password)
      login(@autor)
    else
      redirect_to login_path, flash: { error: "Email o Password incorrecto"}
    end
  end

  def show
    @current_autor = current_autor
  end

  def destroy
    logout
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/autors/book.html.erb
<h1>List of Books</h1>

<% if flash[:notice] %>
	<div>
		<%= flash[:notice] %>
	</div>
<% end %>

<table border ="1" class="table table-striped" style="width: 750px; text-align: center">
	<thead>
		<tr>
			<th style="text-align: center">Autor</th>
			<th style="text-align: center">Title</th>
			<th style="text-align: center">Category</th>
			<th style="text-align: center">Price</th>
			<th style="text-align: center">Quantity</th>
		</tr>
	</thead>
	<tbody>
		<%- @book.each do |bk| %>
			<tr>
				<td><%= Autor.find_by(id: bk.autor_id).name %></td>
				<td><%= link_to bk.title, book_path(bk) %></td>
				<td><%= bk.category %></td>
				<td> Lps. <%= bk.price %> Orden.</td>
				<td>Count</td>
			</tr>
		<%- end %>
	</tbody>
</table>

<p> <%= link_to "New book", new_book_path%> </p>

app/views/autors/new.html.erb
<h1>New Autor</h1>
<p> <em> Ingrese los datos necesarios: </em> </p>

<% if @autor.errors.any? %>
  <div>
    Por favor corrija los siguientes problemas:
    <ul>
      <% @autor.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @autor do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name%>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email%>
  </p>

  <p>
    <%= f.label :password, "Password"%>
    <%= f.password_field :password%>
  </p>

  <p>
    <%= f.label :password_confirmation, "Confirmate Password"%>
    <%= f.password_field :password_confirmation%>
  </p>

  <p>
    <%= f.submit "Create"%>
    <%= link_to "Cancelar", root_path%>
  </p>

<% end %>

app/views/book/new.html.erb
<h1>New Book</h1>
<p> <em> Enter the required data: </em> </p>

<% if @book.errors.any? %>
  <div>
    Please correct the following problems:
    <ul>
      <% @book.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @book do |f| %>
<div>
  <p>
    <%= f.label :title, "Title"%>
    <%= f.text_field :title%>
  </p>

  <p>
    <%= f.label :description%>
    <%= f.text_field :description%>
  </p>

  <p>
    <%= f.label :price%>
    <%= f.number_field :price%>
  </p>

  <p>
    <%= f.label :category%>
    <%= f.select :category, Book.categories %>
  </p>

  <p>
    <%= f.submit "Create", class:"btn btn-default btn-lg" %>
    <%= link_to "Cancel", books_path, class:"btn btn-default btn-lg" %>
  </p>
</div>
<% end %>

app/views/books/_book_orders.erb
<% if orders.any? %>
	<div>
		<h2>Orders: </h2>
		<table border ="1" class="table table-striped" style="width: 500px; text-align: center">
			<thead>
				<th>ID</th>
				<th>Client</th>
				<th>Total</th>
				<th>Quantity</th>
				<th>Fecha inicio</th>
				<th>Fecha final</th>
			</thead>
			<tbody>
				<%= render orders %>
			</tbody>
		</table>
	</div>
<% else %>
	<p style="font-size: 30px"><em>No hay orders.</em></p>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<p> <em> Enter the required data: </em> </p>

<% if @book.errors.any? %>
  <div>
    Please correct the following problems:
    <ul>
      <% @book.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @book do |f| %>
<div>
  <p>
    <%= f.label :title, "Title"%>
    <%= f.text_field :title%>
  </p>

  <p>
    <%= f.label :description%>
    <%= f.text_field :description%>
  </p>

  <p>
    <%= f.label :price%>
    <%= f.number_field :price%>
  </p>

  <p>
    <%= f.label :category%>
    <%= f.select :category, Book.categories %>
  </p>

  <p>
    <%= f.submit "Update", class:"btn btn-default btn-lg" %>
    <%= link_to "Cancel", book_autor_path(current_autor.id), class:"btn btn-default btn-lg" %>
  </p>
</div>
<% end %>

app/views/books/index.html.erb
<h1>List of Books</h1>

<% if flash[:notice] %>
	<div>
		<%= flash[:notice] %>
	</div>
<% end %>

<div>
	<%= form_tag books_path, remote: true, method: :get, class: "js-cars-filter form-inline" do %>
		<div class="form-group">
			<%= text_field_tag :q, params[:q], placeholder: "Palabra Clave", class: "form-control" %>
		</div>
		<%= button_tag type: "submit", class: "btn btn-default" do %>
			<span class="fa fa-search"></span>
		<% end %>
	<% end %>
</div>

<table border ="1" class="table table-striped" style="width: 750px; text-align: center">
	<thead>
		<tr>
			<th style="text-align: center">Autor</th>
			<th style="text-align: center">Title</th>
			<th style="text-align: center">Category</th>
			<th style="text-align: center">Price</th>
			<th style="text-align: center">Quitity Orders</th>
		</tr>
	</thead>
	<tbody>
		<%- @books.each do |bk| %>
			<tr>
				<td><%= Autor.find_by(id: bk.autor_id).name %></td>
				<td><%= link_to bk.title, book_path(bk) %></td>
				<td><%= bk.category %></td>
				<td> Lps. <%= bk.price %> Order.</td>
				<td>Count</td>
			</tr>
		<%- end %>
	</tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>
<p> <em> Enter the required data: </em> </p>

<% if @book.errors.any? %>
  <div>
    Please correct the following problems:
    <ul>
      <% @book.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @book do |f| %>
<div>
  <p>
    <%= f.label :title, "Title"%>
    <%= f.text_field :title%>
  </p>

  <p>
    <%= f.label :description%>
    <%= f.text_field :description%>
  </p>

  <p>
    <%= f.label :price%>
    <%= f.number_field :price%>
  </p>

  <p>
    <%= f.label :category%>
    <%= f.select :category, Book.categories %>
  </p>

  <p>
    <%= f.submit "Create", class:"btn btn-default btn-lg" %>
    <%= link_to "Cancel", book_autor_path(current_autor.id), class:"btn btn-default btn-lg" %>
  </p>
</div>
<% end %>

app/views/books/show.html.erb
<h1 style="font-size: 100px"><%= @book.title %></h1>
<% if flash[:notice] %>
  <div style="background: yellow">
    <%= flash[:notice] %>
  </div>
<% end %>
<ul>
  <li>
    ID:
    <strong><%= @book.id %></strong>
  </li>
	<li>
		Title:
		<strong><%= @book.title %></strong>
	</li>
	<li>
		Descripcion:
		<strong><%= @book.description %></strong>
	</li>
  <li>
    Price:
    <strong>Lps. <%= @book.price %></strong>
  </li>
  <li>
    Category:
    <strong><%= @book.category %></strong>
  </li>
  <li>
    Total Orders:
    <strong><%= total_orders(@book.orders) %></strong>
  </li>
</ul>

<%= render partial: "book_orders", locals: {orders: @book.orders} %>


<% if current_autor == Autor.find_by(id: @book.autor_id) %>
  <p> <%= link_to "Edit", edit_book_path(@book.id)%> </p>
<% end %>
<p> <%= link_to "New Order", new_book_order_path(@book.id)%> </p>
<% unless @book.orders.any? %>
  <p> <%= link_to "Delete", book_path(@book.id), method: :delete%> </p>
<% end %>

app/views/home/index.html.erb
<div>
  <%= image_tag("biblioteca.png") %>
  <p style= "font-size: 30px">
    La Biblioteca mas completa a tu alcanze!
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Bibliotecario</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

 <!-- Navigation -->

<nav class="navbar navbar-light" style="background-color: #654321; font-size: 25px" role="navigation">
    <% if current_autor %>
  <a class="navbar-brand">Order-A-Book - <%= current_autor.name %> </a>
  <%else%>
    <a class="navbar-brand">Order-A-Book </a>
  <% end%>
  <ul class="nav navbar-nav navbar-right">
    <li class="nav-item">
      <%= link_to "Home", root_path %>
    </li>

    <li class="nav-item">
      <%= link_to "Books", books_path %>
    </li>

    <% if current_autor %>

    <li class="nav-item">
      <%= link_to "My Books", book_autor_path(current_autor.id) %>
    </li>

    <li class="nav-item" style="padding-right: 130px">
      <%= link_to "Log Out", logout_path, data: {method: :delete} %>
    </li>

    <% else%>

    <li class="nav-item">
      <%= link_to "Sign In", login_path %>
    </li>

    <li class="nav-item" style="padding-right: 130px">
      <%= link_to "Sign Up", new_autor_path %>
    </li>

    <%end%>

  </ul>

</nav>

<div align= "center">
    <body background = "https://files.graphiq.com/2307/media/images/Light_Gray_429810_i0.png">
    <%= yield %>
  </div>

  </body>
</html>

app/views/orders/_rent.html.erb
<tr>
	<td><%= order.id %> </td>
	<td><%= order.client %></td>
	<td>Lps. <%= order.total %> </td>
	<td><%= order.Quantity %></td>
	<td><%= format_date(rent.rent_start_at) %> </td>
	<td><%= format_date(rent.rent_end_at) %></td>
</tr>

app/views/orders/new.html.erb
<h1>New Order</h1>
<p> <em> Ingrese los datos necesarios: </em> </p>

<% if @rent.errors.any? %>
  <div>
    Por favor corrija los siguientes problemas:
    <ul>
      <% @rent.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@book, @order] do |f| %>
<div>
  <p>
    <%= f.label :client, "Cliente"%>
    <%= f.text_field :client%>
  </p>

  <p>
    <%= f.label :Quantity%>
    <%= f.number_field :Quantity%>
  </p>

  <p>
    <%= f.submit "Create", class:"btn btn-default btn-lg" %>
    <%= link_to "Cancel", book_path(@book.id), class:"btn btn-default btn-lg" %>
  </p>
</div>
<% end %>